Repository weaviate/healthsearch-demo, pull requests merged in 2023-07, with the labels that each got.

#2 v1.1
  CHANGELOG.md
  README.md
  backend/.gitignore
  backend/api.py
  backend/clear_cache.py
  backend/import_data_to_weaviate.py
  frontend/components/ConsoleCard.tsx
  frontend/components/SidebarCard.tsx
  frontend/package-lock.json
  frontend/package.json
  frontend/pages/index.tsx
  frontend/styles/globals.css
Labels: documentation, enhancement

#3 docker-compose backend context fix
  docker-compose.yml
Labels: bug

#4 Update README.md
  frontend/README.md
Labels: documentation

#8 Update README
  README.md
  backend/.gitignore
  backend/Dockerfile
  backend/README.md
  backend/api.py
  frontend/.eslintrc.json
  frontend/README.md
  frontend/components/ConsoleCard.tsx
  frontend/components/SidebarCard.tsx
  frontend/package.json
  frontend/pages/index.tsx
  frontend/styles/globals.css
  frontend/tailwind.config.js
Labels: documentation

#9 Add dataset with vectors
  README.md
  backend/.gitignore
  backend/README.md
  backend/data/dataset_100_supplements_with_vectors.json
  backend/import_data_to_weaviate.py
  backend/start.sh
Labels: enhancement
